name: Main Branch CI

# Triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Allow this Action's jobs access repository contents and packages in the GitHub
# Container Registry (GHCR)
permissions:
  packages: read
  contents: read
      
env:
  BUILD_LOG_ARTIFACT: "build.log"

jobs:

  #-----------------------------------------------------------------------------
  run-unit-tests:
    # Runner and Container Execution Context
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/michaeldello/stm32-dev:v1.3
      # Run the container as root
      options: --user 0
    
    strategy:
      fail-fast: false
      matrix:
        project: [ blinky ]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          rm -rf build
          cmake -S . -B build -DUNIT_TESTS=ON -DCMAKE_BUILD_TYPE=Debug

      - name: Build All Tests
        run: cmake --build build --parallel

      - name: Run Unit Tests for ${{ matrix.project }}
        run: |
          ctest --test-dir build \
                --output-on-failure
                -L "${{ matrix.project }}"
      
      - name: Generate JUnit for ${{ matrix.project }}
        if: always()
        run: |
          ctest --test-dir build \
                --output-junit "tests-${{ matrix.project }}.xml" \
                -L "${{ matrix.project }}" || true

      - name: Upload Artifact for (${{ matrix.project }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-${{ matrix.project }}
          path: build/tests-${{ matrix.project }}.xml